name: CUU
version: '${project.version}'
main: io.github.cats1337.cuu.CUU
api-version: '1.20'
author: Cats1337
description: Cats UberItems Utilities. Plugin commissioned by linktr.ee/xetho__
website: https://cats1337.github.io
depend:
  - UberItems
  - ProtocolLib
permissions:
  cuu.help:
    description: Allows user to view help
    default: true
  cuu.set:
    description: Allows user to set item information
    default: op
  cuu.get:
    description: Allows user to get item information
    default: op
  cuu.check:
    description: Allows user to check item information
    default: op
  cuu.cancel:
    description: Allows user to cancel rituals
    default: op
  cuu.remove:
    description: Allows user to remove item information
    default: op